import Stripe from 'stripe';

export function createMockSubscription(
  overrides?: Partial<Stripe.Subscription>
): Stripe.Subscription {
  const now = Math.floor(Date.now() / 1000);
  return {
    id: 'sub_mock123',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: false, liability: null },
    billing_cycle_anchor: now,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: null,
    collection_method: 'charge_automatically',
    created: now,
    currency: 'usd',
    current_period_end: now + 2592000, // 30 days
    current_period_start: now,
    customer: 'cus_mock123',
    days_until_due: null,
    default_payment_method: 'pm_mock123',
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: null,
    items: {
      object: 'list',
      data: [
        {
          id: 'si_mock123',
          object: 'subscription_item',
          billing_thresholds: null,
          created: now,
          metadata: {},
          price: {
            id: 'price_starter_mock',
            object: 'price',
            active: true,
            billing_scheme: 'per_unit',
            created: now,
            currency: 'usd',
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: 'prod_starter',
            recurring: {
              aggregate_usage: null,
              interval: 'month',
              interval_count: 1,
              meter: null,
              trial_period_days: null,
              usage_type: 'licensed',
            },
            tax_behavior: 'unspecified',
            tiers_mode: null,
            transform_quantity: null,
            type: 'recurring',
            unit_amount: 2900,
            unit_amount_decimal: '2900',
          },
          quantity: 1,
          subscription: 'sub_mock123',
          tax_rates: [],
        },
      ],
      has_more: false,
      url: '/v1/subscription_items',
    },
    latest_invoice: 'in_mock123',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: 'off',
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    schedule: null,
    start_date: now,
    status: 'active',
    test_clock: null,
    transfer_data: null,
    trial_end: null,
    trial_settings: { end_behavior: { missing_payment_method: 'create_invoice' } },
    trial_start: null,
    ...overrides,
  } as Stripe.Subscription;
}

export function createMockCheckoutSession(
  overrides?: Partial<Stripe.Checkout.Session>
): Stripe.Checkout.Session {
  const now = Math.floor(Date.now() / 1000);
  return {
    id: 'cs_test_mock123',
    object: 'checkout.session',
    after_expiration: null,
    allow_promotion_codes: null,
    amount_subtotal: 2900,
    amount_total: 2900,
    automatic_tax: { enabled: false, liability: null, status: null },
    billing_address_collection: null,
    cancel_url: 'http://localhost:3000/pricing',
    client_reference_id: 'user_123',
    client_secret: null,
    consent: null,
    consent_collection: null,
    created: now,
    currency: 'usd',
    currency_conversion: null,
    custom_fields: [],
    custom_text: {
      after_submit: null,
      shipping_address: null,
      submit: null,
      terms_of_service_acceptance: null,
    },
    customer: 'cus_mock123',
    customer_creation: 'always',
    customer_details: {
      address: null,
      email: 'test@example.com',
      name: 'Test User',
      phone: null,
      tax_exempt: 'none',
      tax_ids: [],
    },
    customer_email: 'test@example.com',
    expires_at: now + 3600,
    invoice: null,
    invoice_creation: null,
    livemode: false,
    locale: null,
    metadata: {
      user_id: 'user_123',
      plan_name: 'starter',
    },
    mode: 'subscription',
    payment_intent: null,
    payment_link: null,
    payment_method_collection: 'always',
    payment_method_configuration_details: null,
    payment_method_options: null,
    payment_method_types: ['card'],
    payment_status: 'paid',
    phone_number_collection: { enabled: false },
    recovered_from: null,
    redirect_on_completion: 'always',
    return_url: null,
    saved_payment_method_options: null,
    setup_intent: null,
    shipping_address_collection: null,
    shipping_cost: null,
    shipping_details: null,
    shipping_options: [],
    status: 'complete',
    submit_type: null,
    subscription: 'sub_mock123',
    success_url: 'http://localhost:3000/dashboard?success=true',
    total_details: {
      amount_discount: 0,
      amount_shipping: 0,
      amount_tax: 0,
    },
    ui_mode: 'hosted',
    url: null,
    ...overrides,
  } as Stripe.Checkout.Session;
}

export function createMockInvoice(
  overrides?: Partial<Stripe.Invoice>
): Stripe.Invoice {
  const now = Math.floor(Date.now() / 1000);
  return {
    id: 'in_mock123',
    object: 'invoice',
    account_country: 'US',
    account_name: 'Test Account',
    account_tax_ids: null,
    amount_due: 2900,
    amount_paid: 2900,
    amount_remaining: 0,
    amount_shipping: 0,
    application: null,
    application_fee_amount: null,
    attempt_count: 1,
    attempted: true,
    auto_advance: true,
    automatic_tax: { enabled: false, liability: null, status: null },
    billing_reason: 'subscription_create',
    charge: 'ch_mock123',
    collection_method: 'charge_automatically',
    created: now,
    currency: 'usd',
    custom_fields: null,
    customer: 'cus_mock123',
    customer_address: null,
    customer_email: 'test@example.com',
    customer_name: 'Test User',
    customer_phone: null,
    customer_shipping: null,
    customer_tax_exempt: 'none',
    customer_tax_ids: [],
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    discounts: [],
    due_date: null,
    effective_at: now,
    ending_balance: 0,
    footer: null,
    from_invoice: null,
    hosted_invoice_url: 'https://invoice.stripe.com/i/mock',
    invoice_pdf: 'https://invoice.stripe.com/i/mock/pdf',
    issuer: { type: 'self' },
    last_finalization_error: null,
    latest_revision: null,
    lines: {
      object: 'list',
      data: [],
      has_more: false,
      url: '/v1/invoices/in_mock123/lines',
    },
    livemode: false,
    metadata: {},
    next_payment_attempt: null,
    number: 'INV-0001',
    on_behalf_of: null,
    paid: true,
    paid_out_of_band: false,
    payment_intent: 'pi_mock123',
    payment_settings: {
      default_mandate: null,
      payment_method_options: null,
      payment_method_types: null,
    },
    period_end: now + 2592000,
    period_start: now,
    post_payment_credit_notes_amount: 0,
    pre_payment_credit_notes_amount: 0,
    quote: null,
    receipt_number: null,
    rendering: null,
    rendering_options: null,
    shipping_cost: null,
    shipping_details: null,
    starting_balance: 0,
    statement_descriptor: null,
    status: 'paid',
    status_transitions: {
      finalized_at: now,
      marked_uncollectible_at: null,
      paid_at: now,
      voided_at: null,
    },
    subscription: 'sub_mock123',
    subscription_details: { metadata: null },
    subtotal: 2900,
    subtotal_excluding_tax: 2900,
    tax: null,
    test_clock: null,
    total: 2900,
    total_discount_amounts: [],
    total_excluding_tax: 2900,
    total_tax_amounts: [],
    transfer_data: null,
    webhooks_delivered_at: now,
    ...overrides,
  } as Stripe.Invoice;
}
